name: Build


on: [push]

env:

  TOOLCHAIN: system-gcc

  INSTALLER: yes

jobs:

  build:

    runs-on: ubuntu-22.04

    strategy:

      fail-fast: false

     # matrix:

     #   model: [ "G970F,G973F,G975F", "G970F", "G973F", "G975F"]

        

    steps:

      - uses: actions/checkout@v3


      - name: Install dependencies

        #env:

         # DEBIAN_FRONTEND: noninteractive

        run: sudo apt-get install -y -qq  gcc gcc-aarch64-linux-gnu


          

      
           

      
      - name: autogene
        run: |
          ls -lR \
          /home/runner/work/mono-android/mono-android/autogene.sh

      - name: configure

        run: |

          /home/runner/work/mono-android/mono-android/configure
          
      - name: make

        run: |

          cd /home/runner/work/mono-android/mono-android
          make


  

      
      
#      - name: Upload Kernel Images
#
#        if: env.INSTALLER != 'yes'

#        uses: actions/upload-artifact@v2

#        with:

#          name: CruelKernel-${{ matrix.model }}

#          path: '*.img'

#          if-no-files-found: error

                 

      
